// Generated by CoffeeScript 1.4.0
(function() {
  var $, generate, hs;

  $ = jQuery;

  hs = window.hubspotShare;

  generate = function(shareType, data) {
    var c;
    if (shareType === 'twitter') {
      c = hs.TwitterShare;
    } else if (shareType === 'facebook') {
      c = hs.FacebookShare;
    } else {
      return;
    }
    return new c(data).render();
  };

  $(function() {
    return $('.create-code').click(function(evt) {
      var $button, $form, $target, code, formVals, pair, shareType, valArray, valStr, vals, _i, _len;
      evt.preventDefault();
      $button = $(this);
      $form = $button.parents('form');
      $target = $($form.data('output'));
      shareType = $form.attr('id');
      valStr = $form.formSerialize();
      valArray = valStr.split('&');
      formVals = {};
      for (_i = 0, _len = valArray.length; _i < _len; _i++) {
        pair = valArray[_i];
        vals = pair.split('=');
        formVals[vals[0]] = vals[1];
      }
      if (shareType === 'twitter') {
        formVals.bindOpts = {};
        formVals.bindOpts[formVals.bindEvent] = function() {
          var img;
          img = new Img();
          img.onload(function() {
            return window.location.href = formVals.redirect_url;
          });
          return img.src = formVals.bindCallback;
        };
      } else if (shareType === 'facebook') {
        formVals.success = function() {
          var img;
          img = new Img();
          img.onload(function() {
            return window.location.href = formVals.redirect_url;
          });
          return img.src = formVals.bindCallback;
        };
      }
      code = generate(shareType, formVals);
      return $target.val(code);
    });
  });

}).call(this);
