// Generated by CoffeeScript 1.4.0
(function() {
  var $, hs;

  $ = jQuery;

  hs = window.hubspotShare;

  $(function() {
    return $('.create-code').click(function(evt) {
      var $button, $form, $live, $target, c, code, formVals, pair, shareInstance, shareType, valArray, valStr, vals, _i, _len;
      evt.preventDefault();
      $button = $(this);
      $form = $button.parents('form');
      $target = $($form.data('output'));
      $live = $($form.data('test-output'));
      shareType = $form.attr('id');
      valStr = decodeURIComponent($form.formSerialize());
      valArray = valStr.split('&');
      formVals = {};
      for (_i = 0, _len = valArray.length; _i < _len; _i++) {
        pair = valArray[_i];
        vals = pair.split('=');
        formVals[vals[0]] = vals[1];
      }
      if (shareType === 'twitter') {
        c = hs.TwitterShare;
      } else if (shareType === 'facebook') {
        c = hs.FacebookShare;
      }
      shareInstance = new c(formVals);
      code = shareInstance.render();
      $target.val(code);
      return $live.html(code);
    });
  });

}).call(this);
